name: Step 0 # Start Exercise

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: write
  issues: write

env:
  STEP_1_FILE: ".github/steps/1-step.md"

jobs:
  start_exercise:
    if: |
      !github.event.repository.is_template
    name: Start Exercise
    uses: skills/exercise-toolkit/.github/workflows/start-exercise.yml@v0.7.0
    with:
      exercise-title: "Customize Your GitHub Copilot Experience"
      intro-message: "Learn how to customize GitHub Copilot to work better for your team and projects."

  update_assignment_dates:
    name: Update assignment dates in config.json
    runs-on: ubuntu-latest
    needs: [start_exercise]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update assignment dates
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Helper function to get date with offset
            const getDate = (daysOffset) => {
              const date = new Date();
              date.setDate(date.getDate() + daysOffset);
              return date.toISOString().split('T')[0];
            };

            // Read and update config.json
            const config = JSON.parse(fs.readFileSync('config.json', 'utf8'));

            // Update assignment dates
            config.assignments[0].dueDate = getDate(-45);  // 45 days ago
            config.assignments[1].dueDate = getDate(-30);  // 30 days ago
            config.assignments[2].dueDate = getDate(-20);  // 20 days ago
            config.assignments[3].dueDate = getDate(14);   // 2 weeks ahead

            // Write updated config.json
            fs.writeFileSync('config.json', JSON.stringify(config, null, 2) + '\n');

      - name: Commit updated config.json
        uses: EndBug/add-and-commit@v9
        with:
          add: "config.json"
          message: "Update assignment due dates for exercise start"
          default_author: github_actions

  post_next_step_content:
    name: Post next step content
    runs-on: ubuntu-latest
    needs: [start_exercise]
    env:
      ISSUE_NUMBER: ${{ needs.start_exercise.outputs.issue-number }}
      ISSUE_REPOSITORY: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get response templates
        uses: actions/checkout@v4
        with:
          repository: skills/exercise-toolkit
          path: exercise-toolkit
          ref: v0.7.0

      - name: Create comment - add step content
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_1_FILE }}
          vars: |
            full_repo_name: ${{ github.repository }}

      - name: Create comment - watching for progress
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: exercise-toolkit/markdown-templates/step-feedback/watching-for-progress.md

      - name: Enable next step workflow
        run: |
          gh workflow enable "Step 1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
